---
version: 8.0.2
slug: git_pull_tothemoonsands
name: Git pull (TotheMoonSands)
description: Simple git pull to update the local configuration
url: https://github.com/tothemoonsands/ha_git_pull/tree/master/git_pull
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: manual
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
init: false
map:
  - config:rw
options:
  repository: ""
  git_branch: master
  git_remote: origin
  auto_restart: false
  restart_ignore:
    - ui-lovelace.yaml
    - .gitignore
  git_command: pull
  git_prune: false
  deployment_key: ""
  deployment_user: ""
  deployment_password: ""
  deployment_key_protocol: rsa
  debug: false
  config_apply_mode: restart
  repeat:
    active: false
    interval: 300
schema:
  repository: str
  git_branch: str
  git_remote: str
  auto_restart: bool
  restart_ignore:
    - str
  git_command: list(pull|reset)
  git_prune: bool
  deployment_key: str
  deployment_user: str
  deployment_password: password
  deployment_key_protocol: match(rsa|dsa|ecdsa|ed25519|rsa)
  debug: bool
  config_apply_mode: list(restart|quick_reload)
  repeat:
    active: bool
    interval: int
startup: services
